### ISSUE TITLE
Refactor transaction gossiping and management

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/optimint#100]
#97 attempts to validate transactions that are gossiped, but this makes transaction gossiping and management overly confusing. We are still trying to improve upon the current design.

We do not want to gossip invalid transactions, and in libp2p messages are gossiped automatically unless stopped. So we have to check the transactions by registering a validator. This validator uses the mempool to check the validity of the transactions, which ends up either adding valid transaction to the mempool, rejecting invalid ones, or approving transactions that have already been added to the mempool without rechecking them.

This results in a messy solution that is difficult to grok and will likely cause further problems down the line. Mainly, the transactions that are submitted to the node are gossiped in the rpcclient package. 

During a sync call, we decided that we will attempt to merge #97 after it is ensured that everything is working as intended, then we will update to the latest version of pubsub and tendermint’s mempool. After that, we will be in a better place to make a decision on what to do next. Any proposed changes will likely be implemented after devnet, as that is the main priority.

any potential solution to this is blocked by #98 and #99

**Comment by tzdybal** [comment]
This is very interesting and relevant piece of docs: https://docs.tendermint.com/v0.34/spec/abci/apps.html#mempool-connection

> Note that CheckTx doesn't have to check everything that affects transaction validity; the expensive things can be skipped. In fact, CheckTx doesn't have to check anything; it might say that any transaction is a valid transaction. Unlike DeliverTx, CheckTx is just there as a sort of weak filter to keep invalid transactions out of the blockchain.

I think it's safe to take following assumptions:
1. CheckTx is lightweight method.
1. CheckTx shouldn't change the application state.
 
Because of those assumptions, we can:
1. Use `CheckTx` directly via proxy app / mempool connection (not the mempool module).
1. Call `CheckTx` more than once (rechecking is done even by mempool module). 

I would suggest to separate validation from execution/handling and keep `validator` and `handler`.

**Comment by evan-forbes** [comment]
CheckTx certainly doesn't modify application state, but as mentioned in the first paragraph docs linked
> The mempool Connection should maintain a CheckTxState to sequentially process pending transactions in the mempool that have not yet been committed.

The docs linked also describe the tight coupling between the `CheckTxState` and the mempool, where the mempool has to be locked.
> However, before calling Commit, Tendermint will lock and flush the mempool connection, ensuring that all existing CheckTx are responded to and no new ones can begin.

I think that should be interpreted as only the mempool should be calling CheckTx. We can get a better view of how the sdk relies on this assumption.
per the sdk docs: https://docs.cosmos.network/master/core/baseapp.html
- checkState: This state is updated during CheckTx, and reset on Commit.

this test specifically tests that checkTx keeps track of state until commit is called
https://github.com/cosmos/cosmos-sdk/blob/1178626e50b6c6a60149aa6cd14017607f98cd99/baseapp/baseapp_test.go#L924-L984

If we don't do this, then I think there could be some really weird edge cases, where the `checkState` get's messed up and causes some transactions to be incorrectly determined to be valid/invalid. 

this is what led me to believe that we would have to design #97 with this in mind and use the mempool instead of the proxy app connections. I still think this is the case, and should move forward with merging #97

**Comment by tzdybal** [comment]
Cosmos documentation mentioned by @evan-forbes: https://docs.cosmos.network/master/core/baseapp.html

Crucial parts: 
* https://docs.cosmos.network/master/core/baseapp.html#state-updates
  > The BaseApp maintains two primary volatile states and a root or main state. The main state is the canonical state of the application and the volatile states, checkState and deliverState, are used to handle state transitions in-between the main state made during Commit.
* https://docs.cosmos.network/master/core/baseapp.html#checktx-state-updates
* https://docs.cosmos.network/master/core/baseapp.html#checktx
  > CheckTx() can perform both stateful and stateless checks, but developers should strive to make them lightweight.
  
  > During each step of CheckTx(), a special volatile state called checkState is updated. This state is used to keep track of the temporary changes triggered by the CheckTx() calls of each transaction without modifying the main canonical state . For example, when a transaction goes through CheckTx(), the transaction's fees are deducted from the sender's account in checkState. If a second transaction is received from the same account before the first is processed, and the account has consumed all its funds in checkState during the first transaction, the second transaction will fail CheckTx() and be rejected. In any case, the sender's account will not actually pay the fees until the transaction is actually included in a block, because checkState never gets committed to the main state. The checkState is reset to the latest state of the main state each time a blocks gets committed.

**Comment by tzdybal** [comment]
Ref: #126

**Comment by tzdybal** [comment]
This was actually resolved by #126
