### ISSUE TITLE
Data root must commit to shares

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/optimint#133]
Currently the `DataHash` field in the header commits to nothing. In following with the vanilla Tendermint/Cosmos SDK, it will commit to the Merkle root of transactions.

https://github.com/celestiaorg/optimint/blob/0473227037419b45c27e2efbef12daf9a11a9eda/types/block.go#L22

However, if it commits to transactions then a rollup light client won't actually be able to determine whether the data behind the root is available, since it does DAS on _shares_. In order to resolve this, the `DataHash` must be the Merkle root of the rollup block's transactions in share form, specifically aligned to share size _including_ the block header itself in the rollup block.

**Comment by liamsi** [comment]
> In order to resolve this, the DataHash must be the Merkle root of the rollup block's transactions in share form

Can this be described more concretely? ideally in pseudo-code for instance?

**Comment by adlerjohn** [comment]
Hopefully this is clear enough:

1. Serialize the entire rollup block (header + data + anything else). At this point you don't yet know the share layout, so just leave the `DataHash` field in the header as random garbage.
2. Split serialized data into shares.
3. Now go back and compute the Merkle root of all the shares, then write it into the slice in the serialized bytes that corresponds to the `DataHash` field.

This is obviously non-trivial, since it involves some ugly post-serialization processing. You might also want to ensure that the header itself is padded to share alignment or something.

**Comment by adlerjohn** [comment]
While starting the ADR over the weekend and considering alternatives, something came to mind. What if the rollup block header simple didn't commit to the rollup block's transactions at all (which is the status quo, technically)? The rollup nodes would use the PayForMessage commitment as a commitment to _both_ the rollup block header and rollup block data. It would be a little messy since the first transaction wouldn't be start at the leftmost branch, but I don't see why it wouldn't work. You'd just need some cute scheme to distinguish the rollup block header from rollup block data, but a simple standard should suffice.

Do you see anything wrong with this @liamsi @tzdybal? If not, it's probably the easiest path forward.

(For posterity, since it may be useful later, my idea was
1. Put the rollup block header _after_ the transaction data (i.e. make it a footer), so that the first transaction starts at the first share, aligned.
2. Add a header (optional) and footer field to WirePayForMessage, one per witness. Then append the appropriate footer to construct a distinct message without actually having to send different messages completely when you only need small variations.
)
