### ISSUE TITLE
Create the first end to end CI test

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/optimint#169]
In preparation for devnet, we need an end to end test for optimint not unlike the one included in tendermint. In place of a full blown data availability layer, we will use the mock gprc DALC created in #158 to simulate a data availability layer. We will not cover all desired test cases in this iteration, so we should aim for a level of flexibility that allows for arbitrary future tests to be added without a huge amount of change.

Initial tests should include:
- [ ] test restarting all node types
- [ ] syncing a new node full node from scratch
- [ ] add transaction via one non-aggregator node, and query on another
- [ ] recovery from being disconnected from the DALC

**Comment by tzdybal** [comment]
Closing in favor of #518.
