### ISSUE TITLE
Map rollup block height to data availability layer block height

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/optimint#180]
It would be optimal to keep track of which data availability layer block height corresponds to the optimint rollup block height. 

note: we will not be working on this until after devnet

related to #88

**Comment by liamsi** [comment]
As discussed in person, a very simple (a bit stupid) mapping is actually on-chain: the first Celestia block that contains a rollup block header (can be found by namespace) contains a mapping from Celestia block height -> rollup block height.

**Comment by tzdybal** [comment]
Closing, as it's completely out of date.
