### ISSUE TITLE
Implement GenesisChunked method

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#232]
Implement [GenesisChunked method](https://docs.tendermint.com/master/rpc/#/Info/genesis_chunked), for compatibility with Tendermint RPC.

See: [client.go](https://github.com/celestiaorg/optimint/blob/feb7aab58358d4718b83ff6904a6cec95cac35a5/rpc/client/client.go#L260)

**Comment by mauriceLC92** [comment]
Hey @tzdybal do you mind assigning this task to me?
