### ISSUE TITLE
Implement BlockByHash method

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#234]
Implement [BlockByHash method](https://docs.tendermint.com/master/rpc/#/Info/block_by_hash), for compatibility with Tendermint RPC.

See: [client.go](https://github.com/celestiaorg/optimint/blob/feb7aab58358d4718b83ff6904a6cec95cac35a5/rpc/client/client.go#L342)

**Comment by mauriceLC92** [comment]
Hey @tzdybal as discussed I am keen to tackle this issue. Could you assign it to me please?

**Comment by tzdybal** [comment]
Resolved by #256
