### ISSUE TITLE
Implement Tx method

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#238]
Implement [Tx method ](https://docs.tendermint.com/master/rpc/#/Info/tx), for compatibility with Tendermint RPC.

Tendermint implementation: [rpc/core/tx.go#L20](https://github.com/celestiaorg/celestia-core/blob/b00cac936825b61c1f60fd888794d1d77339f0b9/rpc/core/tx.go#L20)

See: [client.go](https://github.com/celestiaorg/optimint/blob/feb7aab58358d4718b83ff6904a6cec95cac35a5/rpc/client/client.go#L361)

**Comment by mauriceLC92** [comment]
Hey @tzdybal could you assign this issue to me?
