### ISSUE TITLE
Implement single round fraud proofs using microblocks

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#249]

**Comment by liamsi** [comment]
A SDK Tx can contain a lot of SDK messages (that modify the state machine). That is sth to keep in mind with the micro block approach.

**Comment by jbowen93** [comment]
Academic example repo: https://github.com/asonnino/fraudproofs-prototype

**Comment by jbowen93** [comment]
We aren't doing microblocks.
