### ISSUE TITLE
Handle multiple potential blocks per data availability layer block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/optimint#277]
The dalc currently assumes that there is only a single optimint block in a namespace for a given celestia block. Optimint needs to be capable of handling multiple potential blocks per each celestia block. This will involve changing the dalc server to return multiple optimint blocks upon querying for blocks in a given namespace [#56](https://github.com/celestiaorg/dalc/issues/56), along with tying this into how optimint picks valid potential blocks via the app and/or a leader selection rule.

related to #210

**Comment by tzdybal** [comment]
This is actually already implemented (#341).
