### ISSUE TITLE
simple scaffolding tool

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/optimint#28]
The process to create an ORU chain must be as frictionless as possible. Ideally, we should target e.g. for [starport](https://github.com/tendermint/starport) integration as this will easily become the goto way to create SDK-based chains. 

But independent of startport integration we need a simple way to create an ORU chain. Maybe a script that replays the diffs to the SDK to rip out tendermint with optimint is sufficient for an MVP.

**Comment by tzdybal** [comment]
Optimint can be used with Ignite CLI (previously starport) with a single command.
