### ISSUE TITLE
DA API Improvements

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#281]
### What are the problems of existing API?
1. If block returned from DALC fails validation in Optimint, Optimint is not able to continue syncing. There is no way to request next potentially valid block. `BlockRetriever` use Optimint block height.
1. Celestia block may contain multiple Optimint blocks. Is there a reason to pass Celestia block boundary information to Optimint? Or is it sufficient to provide block-by-block in order?
    1. Alternative 1: return batch of all Optimint blocks for every Celestia block
    1. Alternative 2: return some meta-information about Celestia block (at least height) with each Optimint block.

### What can't be the argument to `RetrieveBlock`?
* Celestia block height can't be used:
  * to be as generic as possible, API doesn't even require DA to have heights - it might use block hashes only
  * not all Celestia blocks will contain Optimint blocks for given namespace; it's not Optimint responsibility to keep track of those blocks
 * Optimint block height can't be used:
   * DALC is not responsible for block validation, therefore it's not able to return valid block at given Optimint height
   * if block returned for given height is invalid, there is no way to inform DALC to continue searching for a block

### Proposals for argument to `RetrieveBlock`
 * proposal 1: `daN` - **sequence number of Optimint block in given Celestia namespace (or generically "in DA")**
    * in case of invalid block, Optimint can just ask for block `daN+1`
    * Optimint needs to keep track of last `daN` value, to be able to ask for more blocks
    * we assume that DALC is able to iterate over messages in given namespace; it can easily maintain `daN -> Celestia height` mapping/index
  * proposal 2: `daB` - **sequence number of Celestia block containing Optimint blocks in given namespace**
    * this is for batching of Optimint blocks from each Celestia block
    * Optimint is able to request next batch easily: `daB+1`
    * Optimint can select valid block(s) from each batch
    * `daB -> Celestia height` mapping/index is trivial to implement in DALC

Proposed `daN` as identifier, enables to think about all Optimint blocks in given namespace as a simple sequence. It's unique, ordered identification scheme. From DALC perspective they are just blocks (valid or not). DALC should not be responsible for block validation, and with use of `daN` it doesn't need to know about block validity.

In case we actually need to know about Celestia block boundaries inside Optimint, batching of Optimint blocks can be used with `daB` identification scheme. Each batch can consist of Optimint blocks from single Celestia block. Again, DALC is not responsible for block validation. 

Ref: https://github.com/celestiaorg/dalc/discussions/24

**Comment by tzdybal** [comment]
CC: @liamsi @adlerjohn

**Comment by evan-forbes** [comment]
In synchronous calls, we've discussed an API for the dalc that streams all incoming optimint blocks as they are included in celestia blocks. 

If we did this, we would also want the dalc to notify optimint of celestia blocks that do not contain optimint blocks. This way, if optimint is using tendmerint's proposer selection rules as leader selection rules, the proposer priority can be incremented. 

We also briefly discussed potentially moving some of the mapping between optimint blocks and celestia blocks into optimint, as this could simplify implementing leader selection.

**Comment by tzdybal** [comment]
Agreed change (KISS):
 - use celestia height instead of optimint height in requests
 - return all optimint blocks at given celestia height
 - heights mapping is done completely in optimint
 - if celestia block at given height contains no optimint blocks (in given namespace), simply empty results should be returned (not an error)

In the future, this can be extended to streaming blocks, but for now we keep things simple.

**Comment by musalbas** [comment]
>use celestia height instead of optimint height in requests

But if there's multiple optimint blocks in a Celestia blocks? This is important for micro-blocks for fraud proofs.

**Comment by tzdybal** [comment]
> return all optimint blocks at given celestia height

**Comment by musalbas** [comment]
Oh ok. So the optimint blocks can still have their own internal block heights.

**Comment by tzdybal** [comment]
Yes. Optimint blocks will have it's own heights, and the mapping will be internal to optimint, so DALC will be simplified.

**Comment by musalbas** [comment]
I'm confused about what "return optimint blocks" here means in the context of this API. Does the API have a concept of a "optimint block"? It should only have a concept of messages in Celestia namespaces, and not necessarily know how to parse the messages. What is actually returned?

**Comment by liamsi** [comment]
> [I'm confused about what "return optimint blocks" here means in the context of this API. Does the API have a concept of a "optimint block"? It should only have a concept of messages in Celestia namespaces, and not necessarily know how to parse the messages. What is actually returned?](https://github.com/celestiaorg/optimint/issues/281#issuecomment-1048914995) 

Why shouldn't this API understand how to parse messages into blocks? Maybe the confusion stems from the fact that an optimint block is (similar to a tendermint block) just a bunch of Tx. only the application knows how to parse these Txs but optimint needs optimint blocks.

**Comment by musalbas** [comment]
Not all rollups on Celestia might be optimint rollups, or use the optimint block header format

**Comment by liamsi** [comment]
But this issue (and the API being discussed) is specifically about optimint.

**Comment by musalbas** [comment]
I thought it was about https://github.com/celestiaorg/dalc. Is DALC not supposed to be general-purpose?

**Comment by musalbas** [comment]
The API being discussed is in the DALC repo: https://github.com/celestiaorg/dalc/blob/main/server/server.go#L177

**Comment by liamsi** [comment]
Hmm, I think this was a mix between DALC and the API in Optimint here but indpendent of that, the dalc library already assumes the optimint header format:
https://github.com/celestiaorg/optimint/blob/488b7079f247fbe920250b67dfde3533b085cdeb/proto/optimint/optimint.proto#L68-L72

**Comment by evan-forbes** [comment]
perhaps we could make the dalc more general and also not import celestia-core into optimint by simply copy pasting the necessary types from celestia-core into optimint. This way the dalc would just server normal celestia-core `Message`s, except they'd technically be optimint `Message`s

**Comment by evan-forbes** [comment]
I think that doing this, along with merging a slightly more general version of the gprc server into celestia-node, would allow us to get rid of this repo all together. We wouldn't need to add plugins to celestia-node either, although we might still want to add them so that other teams can still create custom DAS light clients. It would be a bonus tho, not a necessity 

@tzdybal wdyt? would this work?
