### ISSUE TITLE
Wrap errors returned from `Store`

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#288]
In multiple places in the code, errors returned from `Store` are just re-returned. Because of that they are completely non-meaningful.
For example [client.go:351](https://github.com/celestiaorg/optimint/blob/12b445142c811a6d0a77b6f55e87ad1779edb91e/rpc/client/client.go#L351), can return something as generic as "key not found".

All unwrapped errors should be wrapped with meaningful error message, using `fmt.Errorf("meaningful message: %w", err)`.

**Comment by mauriceLC92** [comment]
@tzdybal Do you mind assigning this to me please?

**Comment by tzdybal** [comment]
Sure thing!

**Comment by mauriceLC92** [comment]
@tzdybal should the wrapped errors be returned from the store package?
The example in the issue relates to the rpc client so not sure how extensive the error wrapping should be

**Comment by tzdybal** [comment]
I think it will be enough (at least for now) to just wrap in `store` package. Then, the error message will be something like:
`failed to load block: key not found` and I assume someone calling RPC method will know what method returned this error.
