### ISSUE TITLE
`TestValidatorSetHandling` is flaky/non-deterministic

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#293]
[`TestValidatorSetHandling`](https://github.com/celestiaorg/optimint/blob/main/rpc/client/client_test.go#L578) fails on CI from time to time. It's using `time.Sleep`s  corresponding to `BlockTime` aggregator config. This is "fragile" solution, especially with when running with GitHub actions.

Test should be updated so it's not using `time.Sleep` anymore. Possible solution is to use channel in `EndBlock` mock, to signal about block availability.

**Comment by mauriceLC92** [comment]
@tzdybal could you assign this to me?
