### ISSUE TITLE
Validator address issues

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#306]
The call to get a validator that eventually reaches here (https://github.com/jbowen93/ethermint/blob/main/x/evm/keeper/grpc_query.go#L105) doesn't find the validator.

_Originally posted by @jbowen93 in https://github.com/celestiaorg/optimint/issues/305#issuecomment-1058767799_

**Comment by jbowen93** [comment]
This is resolved.

**Comment by tzdybal** [comment]
Actual issue was a wrong key used in ethermint.
