### ISSUE TITLE
Create a v0.1.2 Release

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/optimint#323]
We should create a new release of Optimint to include commit https://github.com/celestiaorg/optimint/commit/cd1c13dadbdec18a00c7bd1ac5b4f4d0b245e51f 

It's probably easiest to do a [cherry pick release](https://discuss.dgraph.io/t/how-to-create-cherry-pick-prs-into-release-branches/6785) to explicitly exclude commit https://github.com/celestiaorg/optimint/commit/9c2c3749c9cb621ab887575dc204a88831dba7ad because that requires changes to Cevmos.

**Comment by tzdybal** [comment]
Resolved by https://github.com/celestiaorg/optimint/releases/tag/v0.1.2
