### ISSUE TITLE
Error handling in WS code is broken

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#326]
There are multiple issues with error handling in WebSocket handling code. Happy-path works fine, but in case of errors, code panics.

**Comment by jbowen93** [comment]
I'm going to prioritize this because it has bothered me for too long

**Comment by jbowen93** [comment]
First step can be to change https://github.com/celestiaorg/optimint/blob/main/rpc/json/ws.go#L68 from
```
h.logger.Error("expected text message")
```
to
```
h.logger.Debug("expected text message")
```
