### ISSUE TITLE
Print listening address in format used by cosmos-sdk

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#378]
When optimint node is starting, it prints it's listening addresses in multiformat - as used in libp2p.
This is problematic, because configurations/parameters passed to cosmos-sdk app (like `--p2p.seeds`) expect cosmos-sdk format `key@host:port`.
To make things easier, optimint should also print listening addresses in cosmos-sdk format. This way users can just copy-paste address and use in `--p2p.seeds`.

**Comment by jbowen93** [comment]
We should consider whether `p2p.seeds` is the appropriate name for the flag. In Tendermint terminology [seeds](https://docs.tendermint.com/v0.35/tendermint-core/using-tendermint.html#seed) exist to inform nodes to other peers, not to share headers and such.

**Comment by tzdybal** [comment]
Closing in favor of #523.
