### ISSUE TITLE
Investigate how optimint setups up a new proxy app connection

### ISSUE THREAD

**Issue by Manav-Aggarwal** [celestiaorg/optimint#389]
Optimint needs to set up a new cosmos-sdk baseapp in order to execute a transaction when verifying a Fraud Proof. In case of a full node, this new baseapp should be independent of the existing baseapp a full node maintains a connection to

**Comment by tzdybal** [comment]
It's the other way around - optimint is just a library used by cosmos-sdk app. 
1. [NewNode](https://github.com/celestiaorg/optimint/blob/6ac7a2136c0aa1da704ac871e69db8197466e564/node/node.go#L81) is an optimint-side entry-point, called in [cosmos-sdk server/start.go](https://github.com/celestiaorg/cosmos-sdk/blob/0ecef447970bd4382eba1e59eb5243a8dd54c7fb/server/start.go#L295).
2. `clientCreator proxy.ClientCreator` is used only to establish proxy to communicate with application - it's not application itself.
3. Actual application object is [created during application/command](https://github.com/tzdybal/demochain/blob/89b667efb9f55da73a03038a46e7d15b8ace278c/app/app.go#L221) startup and [passed to cosmos-sdk](https://github.com/tzdybal/demochain/blob/89b667efb9f55da73a03038a46e7d15b8ace278c/cmd/demochaind/main.go#L18).

**Comment by tzdybal** [comment]
@Manav-Aggarwal can we close this issue? I think we know everything we need.
