### ISSUE TITLE
Suggestion: Rename repo

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/optimint#481]
optimint is misleading as it sounds it only supports optimistic rollups

Suggestions:

- mint-roll or mintroll
- rollmint
- [Makisu](https://en.m.wikipedia.org/wiki/Makisu) (it makes the rolls; suggested by @tzdybal and my favourite so far)

**Comment by musalbas** [comment]
Or rollmint

**Comment by tzdybal** [comment]
I have no preferences, and the name won't be very visible (there's no binary).
Total brainstorm (random order):
* celestia-roller
* roller
* pulley
* librollup
* celestia-rolling-kit
* celestia-rollup-kit
