### ISSUE TITLE
rpc: Implement endpoints

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/optimint#49]
Tendermint exposes a bunch of RPC endpoints: https://docs.tendermint.com/master/rpc/

Even though those might not be absolutely required for an alternative abci-client, the Cosmos-SDK makes use of them. It would be good if optimint also provided the same RPC endpoints as tendermint does.

Implementation is tracked here: #44

**Comment by tzdybal** [comment]
Updated tracking issues: 
- [ ] https://github.com/celestiaorg/optimint/issues/216
- [ ] https://github.com/celestiaorg/optimint/issues/217
