### ISSUE TITLE
RPC communication with lazyledger-app

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#60]
LazyLedger Data Availability client implementation will use RPC to communicate with lazyledger-app instance.
There were few not-working attempts to achieve this:
 * using (legacy) JSONRPC: https://github.com/lazyledger/optimint/pull/53/commits/995354c5d98383f5cbd590a391d2371f3eb67238
 * using gRPC: https://github.com/lazyledger/optimint/pull/53/commits/153a7a696db8ab7d3146100efe6a19d4d69f6df4 

It is possible, that some changes are also required in lazyledger-app to enable correct handling of `PayForMessage` message.
I [tried to enable](https://github.com/tzdybal/lazyledger-app/tree/tzdybal/easy_pfm) the [gRPC endpoint](https://docs.cosmos.network/master/migrations/rest.html).

Blocked by: https://github.com/lazyledger/lazyledger-app/issues/23

**Comment by evan-forbes** [comment]
can this be closed?
