### ISSUE TITLE
Data Availability layer API

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#8]
To keep the greatest flexibility, we start with the following very limited interface and extend it only if necessary for implementing using LazyLedger as a DA layer (certainly in a way that would not limit developers to use other DA layers though):

```go
// TODO define an enum of different non-happy-path cases
// that might need to be handled by Optimint independent of
// the underlying DA chain.
type StatusCode uint64

type ResultSubmitBlock struct {
  // Code is to determine if the action succeeded.
  Code StatusCode
  // Not sure if this needs to be bubbled up to other
  // parts of Optimint.
  // Hash hash.Hash
}

type DataAvailabilityLayerClient interface {
  Start() error
  Stop() error

  // SubmitBlock submits the passed in block to the DA layer.
  // This should create a transaction which (potentially)
  // triggers a state transition in the DA layer.
  SubmitBlock(block types.Block) ResultSubmitBlock
}
```

**Comment by liamsi** [comment]
This should also be captured in an ADR when the implementation is started.

**Comment by tzdybal** [comment]
ref: #53

**Comment by tzdybal** [comment]
I think we should add one more method - `Init` and pass configuration there. Alternatively we can pass configuration directly to `Start`.

Different implementations will require different config params, so for maximum flexibility I think it would be best to use just a string as a config - implementation can then decode it as YAML/TOML/JSON, whatever.

```go
func Init(config string) error
```

**Comment by liamsi** [comment]
Is this issue still necessary? Given that the DACL exists? Closing now. Feel free to open.
