### ISSUE TITLE
Add separate key for aggregator signatures

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#89]
As pointed out by @evan-forbes in https://github.com/celestiaorg/optimint/pull/82#discussion_r677631765

Aggregator signing key should be separate from key used for P2P.

**Comment by hiddentao** [comment]
I shall have a go at this.

**Comment by mauriceLC92** [comment]
@tzdybal could you please assign this issue to me?

**Comment by tzdybal** [comment]
Resolved by #309
