### ISSUE TITLE
Invalid transactions are gossiped in P2P network

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#93]
Currently, gossiping relies purely on libp2p, with no validation. Even invalid transactions are propagated. Malicious node can spam the network with invalid transactions.
Ideally, this behavior should be limited; each node should not propagate invalid transaction to it's peers.

This can be implemented using [RegisterTopicValidator](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub?utm_source=godoc#PubSub.RegisterTopicValidator). `TopicValidator` should call `CheckTx` to ensure, that only valid transactions are propagated.

**Comment by evan-forbes** [comment]
wait, isn't CheckTx already called before a tx is inserted into the mempool?
https://github.com/celestiaorg/optimint/blob/4c58a3ecb643fb9bb1254d97a1b5a9fc8ac8f0a1/node/node.go#L127-L131

and then it's only gossiped after it enters the mempool? 
https://github.com/celestiaorg/optimint/blob/4c58a3ecb643fb9bb1254d97a1b5a9fc8ac8f0a1/node/node.go#L163-L168

are we still propogating potentially invalid transactions somewhere?

**Comment by evan-forbes** [comment]
ahh, just read #94 
> This is incorrect behavior because libp2p is responsible for delivering messages to all subscribers.

**Comment by Wondertan** [comment]
> libp2p automatically publishes everything, is that right?

If PubSub receives a message from one peer, it automatically resends it to its other peers. No need to republish, so that's right.

> We just have to add an extra CheckTx via the machanism linked?

Ideally, you would extend the recently added `Gossip` to also pass TopicValidator to the underlying pubsub.Topic.

cc @tzdybal
