### ISSUE TITLE
Update pubsub

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/optimint#98]
We should try to update pubsub frequently. Currently we are on version v0.4.1, and v0.5.4 is the latest release.

**Comment by liamsi** [comment]
I think dependabot could come to the rescue here. 
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

**Comment by liamsi** [comment]
I don't think we need a particular issue for this now that dependabot was added. We'll try to keep all deps up to date.
